UI-MVC/Controllers/Api/PlayersController.cs
using MedievalMMO.BL;
using MedievalMMO.BL.Domain;
using Microsoft.AspNetCore.Mvc;

namespace MedievalMMO.UI.Web.Controllers.Api;

[ApiController]
[Route("/api/[controller]")]
public class PlayersController : ControllerBase
{
    private readonly IManager _mgr;

    public PlayersController(IManager manager)
    {
        _mgr = manager;
    }
    
    [HttpGet]
    public IActionResult Get()
    {
        IEnumerable<Player> players = _mgr.GetAllPlayers().ToList();

        if (!players.Any())
        {
            return NoContent();
        }
        
        return Ok(players);
    }
}

UI-MVC/Controllers/GuildController.cs
using MedievalMMO.BL;
using MedievalMMO.BL.Domain;
using Microsoft.AspNetCore.Mvc;

namespace MedievalMMO.UI.Web.Controllers;

public class GuildController : Controller
{
    private readonly IManager _mgr;

    public GuildController(IManager manager)
    {
        _mgr = manager;
    }
    
    public IActionResult Details(int guildId)
    {
        Guild guild = _mgr.GetGuild(guildId);
        return View(guild);
    }
}

UI-MVC/Controllers/PlayerController.cs
using MedievalMMO.BL;
using MedievalMMO.BL.Domain;
using MedievalMMO.UI.Web.Models;
using Microsoft.AspNetCore.Mvc;

namespace MedievalMMO.UI.Web.Controllers;

public class PlayerController : Controller
{
    private readonly IManager _mgr;

    public PlayerController(IManager manager)
    {
        _mgr = manager;
    }

    public IActionResult Index()
    {
        IEnumerable<Player> players = _mgr.GetAllPlayers();
        return View(players);
    }
    
    [HttpGet]
    public IActionResult Add()
    {
        return View();
    }
    
    [HttpPost]
    public IActionResult Add(NewPlayerModel newPlayer)
    {
        if (!ModelState.IsValid)
        {
            return View(newPlayer);
        }

        Player player = _mgr.AddPlayer(newPlayer.PlayerName, newPlayer.PlayerBirthdate, newPlayer.PlayerGender, newPlayer.PlayerLevel);
        return RedirectToAction("Details", "Player", new{PlayerId = player.PlayerId});
    }
    
    public IActionResult Details(int playerId)
    {
        Player player = _mgr.GetPlayerWithGuilds(playerId);
        return View(player);
    }
    
    
}

UI-MVC/Views/Player/Add.cshtml
@using MedievalMMO.BL.Domain
@model MedievalMMO.UI.Web.Models.NewPlayerModel

@{
    ViewBag.Title = "Add Player";
    Layout = "_Layout";
}

<h2>Add Player</h2>

<form asp-controller="Player" asp-action="Add" method="post">
    <div>
        <p>
        <label asp-for="@Model.PlayerName">Player Name</label>
        <input asp-for="@Model.PlayerName" class="form-control"/>
        <span asp-validation-for="@Model.PlayerName" class="text-danger"></span>
        </p>
    </div>
    <div>
        <p>
        <label asp-for="@Model.PlayerBirthdate">Player Birthdate</label>
        <input asp-for="@Model.PlayerBirthdate" class="form-control" type="date"/>
        <span asp-validation-for="@Model.PlayerBirthdate" class="text-danger"></span>
        </p>
    </div>
    <div>
        <p>
        <label asp-for="@Model.PlayerGender">Player Gender</label>
        <select asp-for="@Model.PlayerGender" asp-items="new SelectList(Enum.GetValues(typeof(Gender)))" class="form-select">
        </select>
        <span asp-validation-for="@Model.PlayerGender" class="text-danger"></span>
        </p>
    </div>
    <div>
        <p>
        <label asp-for="@Model.PlayerLevel">Player Level</label>
        <input asp-for="@Model.PlayerLevel" class="form-control"/>
        <span asp-validation-for="@Model.PlayerLevel" class="text-danger"></span>
        </p>
    </div>

    <input type="submit" class="btn btn-primary"/>
</form>

UI-MVC/Views/Player/Details.cshtml
@using MedievalMMO.BL.Domain
@model MedievalMMO.BL.Domain.Player

@{
    ViewBag.Title = "Player Details";
    Layout = "_Layout";
}

<h2>Player Details</h2>

<p><strong>Player Id: </strong><span>@Model.PlayerId</span></p>
<p><strong>Player Name: </strong><span>@Model.PlayerName</span></p>
<p><strong>Player Birthdate: </strong><span>@Model.PlayerBirthdate.ToString("yyyy/MM/dd")</span></p>
<p><strong>Player Gender: </strong><span>@(Model.PlayerGender?.ToString() ?? "No Known Gender")</span></p>
<p><strong>Player Level: </strong><span>@(Model.PlayerLevel?.ToString() ?? "No Known Level")</span></p>

<h4>Player is in Guilds:</h4>
<table class="table">
    <tr>
        <td>Guild Id</td>
        <td>Guild Name</td>
        <td>Player Join Date</td>
        <td>Details</td>
    </tr>
    
    @foreach (PlayerGuild pg in Model.PlayerGuilds)
    {
        <tr>
            <td>@pg.GuildId</td>
            <td>@pg.Guild.GuildName</td>
            <td>@pg.PlayerJoinedGuildOn.ToString("yyyy/MM/dd")</td>
            <td><a asp-controller="Guild" asp-action="Details" asp-route-GuildId="@pg.GuildId">Details</a></td>
        </tr>
    }
</table>

<strong><a asp-controller="Player" asp-action="Index">Back to Player Selection</a></strong>

UI-MVC/Views/Player/Index.cshtml
@using MedievalMMO.BL.Domain
@model IEnumerable<MedievalMMO.BL.Domain.Player>

@{
    ViewBag.Title = "List of All Players";
    Layout = "_Layout";
}

<h2>List of All Players</h2>

<table class="table">
    <tr>
        <td>Player Id</td>
        <td>Player Name</td>
        <td>Player Birthdate</td>
        <td>Player Gender</td>
        <td>Player Level</td>
        <td>details Page</td>
    </tr>
@foreach (Player p in Model)
{
    <tr>
        <td>@p.PlayerId</td>
        <td>@p.PlayerName</td>
        <td>@p.PlayerBirthdate.ToString("yyyy/MM/dd")</td>
        <td>@(p.PlayerGender?.ToString() ?? "No Known Gender")</td>
        <td>@(p.PlayerLevel?.ToString() ?? "No Known Level")</td>
        <td><a asp-controller="Player" asp-action="Details" asp-route-playerId="@p.PlayerId">Details</a></td>
    </tr>
}
</table>